language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
   - dcleal@redhat.com
   - raphael.pinson@camptocamp.com
env: ["PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0", "PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0", "PUPPET=3.2.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0", "PUPPET=3.2.0 RUBY_AUGEAS=0.5", "PUPPET=3.4 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true", "PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0", "PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0", "PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0", "PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD", "PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD", "PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.0.0 LENSES=HEAD", "PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.1.0 LENSES=HEAD", "PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.1.0 LENSES=el7"]
matrix:
  fast_finish: true
  exclude: [{"rvm"=>"2.0.0", "env"=>"PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.0.0 RUBY_AUGEAS=0.3.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.2.0 RUBY_AUGEAS=0.3.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD"}, {"rvm"=>"2.0.0", "env"=>"PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD"}]
install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "RLs24P20I18PvFHgYbOieTGUEwJzhbQFF4fWgpJSf7iM2Q0bxhNQnUdzDXfLMfRwQ/lQGZSQ6eZ5sr/MdzI/qIT13zHM/B+Fv+ZszE/nNZzVTpjhI6vStQrUAZlD76Tx/QJN5bvu0QjFjGyK9DY26FVHqWcYvDHg0L2sQ269uFU="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
    condition: "$FORGE_PUBLISH = true"
